[theme]
primaryColor = "#1C5CAB"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#EEF2F7"
textColor = "#0B0B0B"
base = "light"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
